* rebuild (for Linux).

diff --git a/Linux/Bin/compile b/Linux/Bin/compile
--- a/Linux/Bin/compile
+++ b/Linux/Bin/compile
@@ -5,18 +5,22 @@ modName=$1
 if [ "$modName" == "OfrontOPM.cmdln" ]; then modName="OfrontOPM"; fi
 
 if [ "$modName" == "OfrontCmd" ] || [ "$modName" == "BrowserCmd" ] || [ "$modName" == "OCatCmd" ] ; then
-  ../Bin/ofront -mse ../../Mod/$modName.Mod
+
+  ../Bin/ofront+ -mse ../../Mod/$modName.Mod
   errCode=$?
-  if [ $errCode != 0 ]; then echo "ERROR #"$errCode; sleep 1000m; fi
+  if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
   gcc $modName.c -s -Os -fno-exceptions -fno-asynchronous-unwind-tables -Wl,--gc-sections -I../Lib/Obj -L../Lib $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} -lOfront -ldl
   errCode=$?
-  if [ $errCode != 0 ]; then echo "ERROR #"$errCode; sleep 1000m; fi
+  if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
+
 else
-  ../Bin/ofront -se ../../Mod/$1.Mod
+
+  ../Bin/ofront+ -se ../../Mod/$1.Mod
   errCode=$?
-  if [ $errCode != 0 ]; then echo "ERROR #"$errCode; sleep 1000m; fi
+  if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
   mv -f $modName.sym ../Sym
   gcc -c $modName.c -s -Os -fno-exceptions -fno-asynchronous-unwind-tables -I../Lib/Obj
   errCode=$?
-  if [ $errCode != 0 ]; then echo "ERROR #"$errCode; sleep 1000m; fi
+  if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
+
 fi
