* Linux64: Bootstrapped.

diff --git a/Linux/Bin/compileC64 b/Linux/Bin/compileC64
--- a/Linux/Bin/compileC64
+++ b/Linux/Bin/compileC64
@@ -6,18 +6,18 @@ if [ "$modName" == "OfrontOPM.cmdln" ]; then modName="OfrontOPM"; fi
 
 if [ "$modName" == "OfrontCmd" ] || [ "$modName" == "BrowserCmd" ] || [ "$modName" == "OCatCmd" ] ; then
 
-  ../Bin64/ofront+ -me ../../Mod/$modName.Mod
+  #../Bin64/ofront+ -me ../../Mod/$modName.Mod
   errCode=$?
-  if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
+  #if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
   gcc $modName.c -s -Os -fno-exceptions -fno-asynchronous-unwind-tables -Wl,--gc-sections -I../Lib/C -I../Lib/Obj64 -L../Lib $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} -lOfront64 -ldl
   errCode=$?
   if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
 
 else
 
-  ../Bin64/ofront+ -se ../../Mod/$1.Mod
+  #../Bin64/ofront+ -se ../../Mod/$1.Mod
   errCode=$?
-  if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
+  #if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
   mv -f $modName.sym ../Sym64
   gcc -c $modName.c -s -Os -fno-exceptions -fno-asynchronous-unwind-tables -I../Lib/C -I../Lib/Obj64
   errCode=$?
diff --git a/Linux/Lib/Bin/compileC64 b/Linux/Lib/Bin/compileC64
--- a/Linux/Lib/Bin/compileC64
+++ b/Linux/Lib/Bin/compileC64
@@ -19,13 +19,13 @@ if [ "$2" == "SYSTEM" ]; then
 else
 
   if [ "$2" == "Platform" ] || [ "$2" == "Heap" ] ; then
-    ../../Bin64/ofront+ -apxe ../../../Lib/Mod/$2.Mod
+    #../../Bin64/ofront+ -apxe ../../../Lib/Mod/$2.Mod
     errCode=$?
-    if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
+    #if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
   else
-    ../../Bin64/ofront+ -se ../../../Lib/Mod/$2.Mod
+    #../../Bin64/ofront+ -se ../../../Lib/Mod/$2.Mod
     errCode=$?
-    if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
+    #if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
 
     mv -f $mod.sym ../Sym64
   fi
