* Linux64: * Heap0 [ ofront+ -apxe ].

diff --git a/Linux/Lib/Test64/TestConsole b/Linux/Lib/Test64/TestConsole
--- a/Linux/Lib/Test64/TestConsole
+++ b/Linux/Lib/Test64/TestConsole
@@ -2,9 +2,9 @@
 
 export OBERON=.:../Sym64
 
-#../../Bin/ofront+ -m ../Test/TestConsole.Mod
-#errCode=$?
-#if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
+../../Bin64/ofront+ -m ../Test/TestConsole.Mod
+errCode=$?
+if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
 
 gcc TestConsole.c -o TestConsole.x -I ../Obj64 -I ../C -L .. -lOfront64
 errCode=$?
diff --git a/Linux/Lib/Test64/TestOoc2RandomNumbers b/Linux/Lib/Test64/TestOoc2RandomNumbers
--- a/Linux/Lib/Test64/TestOoc2RandomNumbers
+++ b/Linux/Lib/Test64/TestOoc2RandomNumbers
@@ -2,9 +2,9 @@
 
 export OBERON=.:../Sym64
 
-#../../Bin/ofront+ -m ../Test/TestOoc2RandomNumbers.Mod
-#errCode=$?
-#if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
+../../Bin64/ofront+ -m ../Test/TestOoc2RandomNumbers.Mod
+errCode=$?
+if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
 
 gcc TestOoc2RandomNumbers.c -o TestOoc2RandomNumbers.x -I ../Obj64 -I ../C -L .. -lOfront64
 errCode=$?
