* Lib/Mod/Platform.Unix.Mod: made compilable.

diff --git a/Linux/Lib/Bin/compile64 b/Linux/Lib/Bin/compile64
--- a/Linux/Lib/Bin/compile64
+++ b/Linux/Lib/Bin/compile64
@@ -3,23 +3,33 @@ export OBERON=.:../C:../Sym64
 
 mod=$2
 if [ "$2" == "Platform.Unix" ]; then mod="Platform"; fi
-if [ "$2" == "Files.Unix" ]; then mod="Files"; fi
-if [ "$2" == "Kernel.Unix" ]; then mod="Kernel"; fi
 if [ "$2" == "Modules.Unix" ]; then mod="Modules"; fi
 
 if [ "$2" == "SYSTEM" ]; then
 
-  ../../Bin/ofront+ -iapxe ../../../Lib/Mod/$2.Mod
+  ## SYSTEM
+  gcc -c ../C/SYSTEM.c -I ../C -s -Os -fno-exceptions -fno-asynchronous-unwind-tables
   errCode=$?
   if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
+
+  ar -rc $1 SYSTEM.o
+  rm SYSTEM.o
+  exit 0
 
 else
 
-  ../../Bin/ofront+ -se ../../../Lib/Mod/$2.Mod
-  errCode=$?
-  if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
-  mv -f $mod.sym ../Sym64
+  if [ "$2" == "Platform" ] || [ "$2" == "Heap" ] ; then
+    ../../Bin/ofront+ -apxe ../../../Lib/Mod/$2.Mod
+    errCode=$?
+    if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
+  else
+    ../../Bin/ofront+ -se ../../../Lib/Mod/$2.Mod
+    errCode=$?
+    if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
 
+    mv -f $mod.sym ../Sym64
+  fi
+  
 fi
 
 gcc -c $mod.c -I ../C -s -Os -fno-exceptions -fno-asynchronous-unwind-tables
