* rebuild (for Linux).

diff --git a/Linux/Lib/Bin/compile b/Linux/Lib/Bin/compile
--- a/Linux/Lib/Bin/compile
+++ b/Linux/Lib/Bin/compile
@@ -2,19 +2,23 @@
 export OBERON=.:../Sym
 
 if [ "$2" == "SYSTEM" ]; then
-  ../../Bin/ofront -iapxe ../Mod/$2.Mod
+
+  ../../Bin/ofront+ -iapxe ../Mod/$2.Mod
   errCode=$?
-  if [ $errCode != 0 ]; then echo "ERROR #"$errCode; sleep 1000m; fi
+  if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
+
 else
-  ../../Bin/ofront -se ../Mod/$2.Mod
+
+  ../../Bin/ofront+ -se ../Mod/$2.Mod
   errCode=$?
-  if [ $errCode != 0 ]; then echo "ERROR #"$errCode; sleep 1000m; fi
+  if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
   mv -f $2.sym ../Sym
+
 fi
 
 gcc -c $2.c -s -Os -fno-exceptions -fno-asynchronous-unwind-tables
 errCode=$?
-if [ $errCode != 0 ]; then echo "ERROR #"$errCode; sleep 1000m; fi
+if [ $errCode != 0 ]; then echo "ERROR #"$errCode; exit 1; fi
 
 ar -rc $1 $2.o
 rm $2.o
