* build "ocat", "ofront", "showdef".

diff --git a/Linux/Lib/Bin/compile b/Linux/Lib/Bin/compile
--- a/Linux/Lib/Bin/compile
+++ b/Linux/Lib/Bin/compile
@@ -3,6 +3,8 @@ export OBERON=.:../Sym
 
 if [ "$2" == "SYSTEM" ]; then
   ../../Bin/ofront -iapxe ../Mod/$2.Mod
+  errCode=$?
+  if [ $errCode != 0 ]; then echo "ERROR #"$errCode; sleep 1000m; fi
 else
   ../../Bin/ofront -se ../Mod/$2.Mod
   errCode=$?
